# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Theme_final.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Theme(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(506, 383)
        self.SaveButton = QtWidgets.QPushButton(Dialog)
        self.SaveButton.setGeometry(QtCore.QRect(130, 270, 81, 41))
        self.SaveButton.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(66, 91, 255, 50);\n"
"border-radius: 15;")
        self.SaveButton.setObjectName("SaveButton")
        
        self.Work = QtWidgets.QPushButton(Dialog)
        self.Work.setGeometry(QtCore.QRect(310, 270, 81, 41))
        self.Work.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(66, 91, 255, 40);\n"
"border-radius: 15;")
        self.Work.setObjectName("Work")
        self.Clock = QtWidgets.QLCDNumber(Dialog)
        self.Clock.setGeometry(QtCore.QRect(140, 40, 240, 89))
        self.Clock.setDigitCount(10)
        self.Clock.display('0:00:00.0')
        self.Clock.setStyleSheet("background-color: rgba(157, 188, 199, 95);\n"                              
"border-radius: 10;")
        self.Clock.setObjectName("Clock")
        self.Background = QtWidgets.QWidget(Dialog)
        self.Background.setGeometry(QtCore.QRect(10, 10, 461, 341))
        self.Background.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.057, y1:0.943182, x2:0.857955, y2:0.125, stop:0 rgba(245, 244, 224, 255), stop:1 rgba(245, 244, 234, 255));\n"
"\n"
"border-radius: 30px\n"
"")
        self.Background.setObjectName("Background")
        self.pushButton_2 = QtWidgets.QPushButton(self.Background)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 130, 41, 41))
        self.pushButton_2.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0.057, y1:0.943182, x2:0.857955, y2:0.125, stop:0 rgba(255, 65, 55, 255), stop:1 rgba(255, 1, 63, 255));\n"
"\n"
"\n"
"border-radius : 20; border : 2px solid black\n"
"font 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.Background)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 130, 41, 41))
        self.pushButton_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.057, y1:0.943182, x2:0.857955, y2:0.125, stop:0 rgba(255,124,87, 255), stop:1 rgba(255,154,87, 255));\n"
"\n"
"border-radius : 20; border : 2px solid black;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.Background)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 180, 41, 41))
        self.pushButton_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.057, y1:0.943182, x2:0.857955, y2:0.125, stop:0 rgba(14, 150, 230, 255), stop:1 rgba(14, 93, 230, 255));\n"
"\n"
"\n"
"border-radius : 20; border : 2px solid black")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.Background)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 180, 41, 41))
        self.pushButton_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.057, y1:0.943182, x2:0.857955, y2:0.125, stop:0 rgba(222, 27, 85, 255), stop:1 rgba(255, 27, 125, 255));\n"
"\n"
"border-radius : 20; border : 2px solid black")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.Background)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 230, 41, 41))
        self.pushButton_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.057, y1:0.943182, x2:0.857955, y2:0.125, stop:0 rgba(48, 243, 110, 255), stop:1 rgba(48, 243, 87, 255));\n"
"\n"
"\n"
"border-radius : 20; border : 2px solid black")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.Background)
        self.pushButton_9.setGeometry(QtCore.QRect(60, 230, 41, 41))
        self.pushButton_9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.057, y1:0.943182, x2:0.857955, y2:0.125, stop:0 rgba(173, 61, 111, 255), stop:1 rgba(210, 30, 205, 255));\n"
"\n"
"border-radius : 20; border : 2px solid black")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.Background)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 280, 41, 41))
        self.pushButton_10.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.057, y1:0.943182, x2:0.857955, y2:0.125, stop:0 rgba(255, 255, 55, 255), stop:1 rgba(232, 225, 20, 200));\n"
"\n"
"\n"
"border-radius : 20; border : 2px solid black")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.Background)
        self.pushButton_11.setGeometry(QtCore.QRect(60, 280, 41, 41))
        self.pushButton_11.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.057, y1:0.943182, x2:0.857955, y2:0.125, stop:0 rgba(245, 244, 224, 255), stop:1 rgba(245, 244, 234, 255));\n"
"\n"
"border-radius : 20; border : 2px solid black")
        self.pushButton_11.setObjectName("pushButton_11")
        
        icons = QtGui.QIcon()#! new code 
        icons.addPixmap(QtGui.QPixmap("Study timer project/Theme window/Home-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3 = QtWidgets.QPushButton(self.Background) #! has to be overlapped by background attrubite
        self.pushButton_3.setGeometry(QtCore.QRect(10, 10, 41, 51))
        self.pushButton_3.setIcon(icons)#! new code
        self.pushButton_3.setIconSize(QtCore.QSize(40,40)) 
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet("image: url(:/homeicon/Home-icon.png);\n"
"background: transparent;\n"
"}")
        
        self.BreakTool = QtWidgets.QToolButton(Dialog)
        self.BreakTool.setGeometry(QtCore.QRect(320, 140, 70, 21))
        self.BreakTool.setStyleSheet("background-color: rgba(66, 91, 255, 0);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.BreakTool.setObjectName("BreakTool")
        self.HideTool = QtWidgets.QToolButton(Dialog)
        self.HideTool.setGeometry(QtCore.QRect(240, 240, 41, 21))
        self.HideTool.setStyleSheet("background-color: rgba(66, 91, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.HideTool.setObjectName("HideTool")
        self.Play = QtWidgets.QPushButton(Dialog)
        self.Play.setGeometry(QtCore.QRect(160, 180, 191, 51))
        self.Play.setStyleSheet("font: 25pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(66, 91, 255, 50);\n"
"border-radius: 15;")
        self.Play.setObjectName("Play")
        self.Background.raise_()
        self.SaveButton.raise_()
        self.Work.raise_()
        self.Clock.raise_()
        self.BreakTool.raise_()
        self.HideTool.raise_()
        self.Play.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SaveButton.setText(_translate("Dialog", "Save"))
        self.Work.setText(_translate("Dialog", "Reset"))
        self.pushButton_2.setText(_translate("Dialog", "Apple"))
        self.pushButton_5.setText(_translate("Dialog", "peach"))
        self.pushButton_6.setText(_translate("Dialog", "Berry"))
        self.pushButton_7.setText(_translate("Dialog", "Pumo"))
        self.pushButton_8.setText(_translate("Dialog", "Kiwi"))
        self.pushButton_9.setText(_translate("Dialog", "Grape"))
        self.pushButton_10.setText(_translate("Dialog", "Lemon"))
        self.pushButton_11.setText(_translate("Dialog", "soft"))
        self.BreakTool.setText(_translate("Dialog", "Break"))
        self.HideTool.setText(_translate("Dialog", "Hide"))
        self.Play.setText(_translate("Dialog", "Play"))
#import themeicons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Theme()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
