# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimerPlayPause.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import timer 
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(666, 394)
        
        Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint) ## new code
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)## new code
        
        
        self.SaveButton = QtWidgets.QPushButton(Dialog)
        
        
        self.SaveButton.setGeometry(QtCore.QRect(130, 270, 81, 41))
        self.SaveButton.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
        
        
"background-color: rgba(66, 91, 255, 50);\n"
"border-radius: 15;\n")
        self.SaveButton.setObjectName("SaveButton")
        self.Reset = QtWidgets.QPushButton(Dialog)
        self.Reset.setGeometry(QtCore.QRect(310, 270, 81, 41))
        self.Reset.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
        
"background-color: rgba(66, 91, 255, 40);\n"
"border-radius: 15;")
        self.Reset.setObjectName("Work")
        self.Clock = QtWidgets.QLCDNumber(Dialog)
        self.Clock.setGeometry(QtCore.QRect(140, 40, 241, 91))
        self.Clock.setStyleSheet("background-color: rgba(66, 91, 255, 70);\n"
"border-radius: 10;")
        self.Clock.setObjectName("Clock")
        self.Background = QtWidgets.QWidget(Dialog)
        self.Background.setGeometry(QtCore.QRect(10, 10, 461, 341))
        self.Background.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.057, y1:0.943182, x2:0.857955, y2:0.125, stop:0 rgba(245, 244, 224, 255), stop:1 rgba(245, 244, 234, 255));\n"## background color ##
"border-radius: 30;")
        self.Background.setObjectName("Background")
        self.BreakTool = QtWidgets.QToolButton(Dialog)
        self.BreakTool.setGeometry(QtCore.QRect(320, 140, 70, 21))
        self.BreakTool.setStyleSheet("background-color: rgba(66, 91, 255, 0);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.BreakTool.setObjectName("BreakTool")
        self.HideTool = QtWidgets.QToolButton(Dialog)
        self.HideTool.setGeometry(QtCore.QRect(240, 240, 41, 21))
        self.HideTool.setStyleSheet("background-color: rgba(66, 91, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.HideTool.setObjectName("HideTool")
        
        ### Saved session tab ###
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Study timer project/Break windows/Save_button_pic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SavedSessions = QtWidgets.QPushButton(Dialog)
        self.SavedSessions.setGeometry(QtCore.QRect(20, 20, 50, 41))
        self.SavedSessions.setIcon(icon)
        self.SavedSessions.setIconSize(QtCore.QSize(41, 41))
        self.SavedSessions.setText("")
        self.SavedSessions.setObjectName("SavedSessions")
        self.SavedSessions.setStyleSheet("background-image: url(Break windows/Save_button_pic.png);") #SAVED SESSIONS on 
        self.SavedSessions.setStyleSheet("background-color: rgba(66, 91, 255, 50);\n"
"border-radius: 150;\n"
"background: transparent;\n"
"}")
        ### Summary tab ###
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Study timer project/Break windows/SummaryButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Summary = QtWidgets.QPushButton(Dialog)
        self.Summary.setGeometry(QtCore.QRect(30, 70, 30, 41))
        self.Summary.setIcon(icon)
        self.Summary.setIconSize(QtCore.QSize(41, 41))
        self.Summary.setStyleSheet("border-image: url(:/newPrefix/SummaryButton.png);")
        self.Summary.setText("")
        self.Summary.setObjectName("Summary")
        self.Summary.setStyleSheet("background-color: rgba(66, 91, 255, 50);\n"
"border-radius: 15;\n"
"background: transparent;\n"
"}")
        ### Theme tab ###
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Study timer project/Break windows/Theme_Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Theme = QtWidgets.QPushButton(Dialog)
        self.Theme.setGeometry(QtCore.QRect(20, 120, 45, 45))
        self.Theme.setIcon(icon2)
        self.Theme.setIconSize(QtCore.QSize(41, 41))
        self.Theme.setText("")
        self.Theme.setObjectName("Theme")
        self.Theme.setStyleSheet("background-color: rgba(66, 91, 255, 50);\n"
"border-radius: 15;\n"
"background: transparent;\n"
"}")
        ### Settings tab ###
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Study timer project/Break windows/Settings_Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings = QtWidgets.QPushButton(Dialog)
        self.Settings.setGeometry(QtCore.QRect(20, 160, 51, 41))
        self.Settings.setIcon(icon3)
        self.Settings.setIconSize(QtCore.QSize(41, 41))
        self.Settings.setText("")
        self.Settings.setObjectName("Settings")
        self.Settings.setStyleSheet("image: url(Settings_Button_pic.png/png);")
        self.Settings.setStyleSheet("background-color: rgba(66, 91, 255, 50);\n"
"border-radius: 15;\n"
"background: transparent;\n"
"}")

        self.Pause = QtWidgets.QPushButton(Dialog)
        self.Pause.setGeometry(QtCore.QRect(160, 180, 191, 51))
        self.Pause.setStyleSheet("font: 25pt \"MS Shell Dlg 2\";\n"
                                 
"background-color: rgba(66, 91, 255, 50);\n"
"border-radius: 15;")
        self.Pause.setObjectName("Pause")
        self.Play = QtWidgets.QPushButton(Dialog)
        self.Play.setGeometry(QtCore.QRect(160, 180, 191, 51))
        self.Play.setStyleSheet("font: 25pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(66, 91, 255, 50);\n"
"border-radius: 15;")
        self.Play.setObjectName("Play")
        self.Pause.raise_()
        self.Background.raise_()
        self.SaveButton.raise_()
        self.Reset.raise_()
        self.Clock.raise_()
        self.BreakTool.raise_()
        self.HideTool.raise_()
        self.SavedSessions.raise_()
        self.Summary.raise_()
        self.Theme.raise_()
        self.Settings.raise_()
        self.Play.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SaveButton.setText(_translate("Dialog", "Save"))
        self.Reset.setText(_translate("Dialog", "Reset"))
        self.BreakTool.setText(_translate("Dialog", "Break"))
        self.HideTool.setText(_translate("Dialog", "Hide"))
        self.Pause.setText(_translate("Dialog", "Pause"))
        self.Play.setText(_translate("Dialog", "Play"))
        
#import timer 


if __name__ == "__main__":
        
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        Dialog.show()
        sys.exit(app.exec_())
